# Generated by Django 5.0.6 on 2024-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, help_text='Укажите id телеграм чата', max_length=50, null=True, verbose_name='id телеграм чата'),
        ),
    ]
