# Generated by Django 5.0.6 on 2024-07-04 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='duration',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_complete',
            field=models.PositiveIntegerField(default=1, help_text='Укажите время на выполнение привычки', verbose_name='Время на выполнение привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Укажите связанную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
    ]
