# Generated by Django 5.0.6 on 2024-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_rename_user_habit_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='duration',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_complete',
            field=models.PositiveIntegerField(default=1, help_text='Укажите время на выполнение привычки', verbose_name='Время на выполнение привычки'),
        ),
    ]
